digest: aa3ea103
name: dataset
profile: '{"num_rows": 134, "num_elements": 1206}'
schema: '{"mlflow_colspec": [{"type": "double", "name": "PassengerId", "required":
  true}, {"type": "double", "name": "Pclass", "required": true}, {"type": "double",
  "name": "Age", "required": true}, {"type": "double", "name": "SibSp", "required":
  true}, {"type": "double", "name": "Parch", "required": true}, {"type": "double",
  "name": "Fare", "required": true}, {"type": "double", "name": "Sex_female", "required":
  true}, {"type": "double", "name": "Embarked_C", "required": true}, {"type": "double",
  "name": "Embarked_Q", "required": true}]}'
source: '{"tags": {"mlflow.user": "LENOVO", "mlflow.source.name": "C:\\Users\\LENOVO\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel_launcher.py",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
