channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=24.0
- pip:
  - mlflow==2.10.2
  - cloudpickle==3.0.0
  - numpy==1.25.2
  - packaging==23.2
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.11.2
name: mlflow-env
